# Generated by Django 5.2.5 on 2026-09-28 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_backfill_question_bank'),
        ('users_manager', '0007_institutiondataexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('classroom_name', models.CharField(max_length=300)),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_manager.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=300)),
                ('student_registration', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='paper_exams.examrun')),
            ],
            options={
                'ordering': ['student_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='paper_exams.examrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('detected', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('review', 'Revisão necessária'), ('graded', 'Corrigido')], default='review', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidence', models.BinaryField(null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='paper_exams.importbatch')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='paper_exams.answersheet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='answersheet',
            constraint=models.UniqueConstraint(fields=('run', 'student'), name='one_sheet_per_student_run'),
        ),
    ]
