# Generated by Django 5.2.5 on 2026-08-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'técnica avaliativa',
                'verbose_name_plural': 'técnicas avaliativas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descrição')),
                ('default_technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_types', to='assessments.assessmenttechnique', verbose_name='técnica padrão')),
            ],
            options={
                'verbose_name': 'tipo de questão avaliativa',
                'verbose_name_plural': 'tipos de questão avaliativa',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='matéria')),
                ('topic', models.CharField(max_length=160, verbose_name='assunto')),
                ('observations', models.JSONField(blank=True, default=list, verbose_name='observações e restrições')),
                ('technique_selected_automatically', models.BooleanField(default=False, verbose_name='técnica selecionada automaticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.assessmenttechnique', verbose_name='técnica avaliativa')),
                ('assessment_types', models.ManyToManyField(related_name='assessments', to='assessments.assessmenttype', verbose_name='tipos de questão avaliativa')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ('-updated_at',),
            },
        ),
    ]
