# Generated by Django 5.2.5 on 2026-09-21 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seed_assessment_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(verbose_name='enunciado')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla escolha'), ('open_ended', 'Discursiva')], default='multiple_choice', max_length=24, verbose_name='formato da questão')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='alternativas')),
                ('correct_answer', models.TextField(blank=True, verbose_name='gabarito ou resposta esperada')),
                ('explanation', models.TextField(blank=True, verbose_name='explicação do gabarito')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='pontuação')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ('order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('assessment', 'order'), name='unique_question_order_per_assessment')],
            },
        ),
    ]
