# Generated by Django 5.2.5 on 2026-09-22 11:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assembly_method',
            field=models.CharField(choices=[('manual', 'Montagem manual'), ('algorithmic', 'Montagem algorítmica'), ('ai_curated', 'Montagem via IA com banco existente'), ('ai_generated', 'Criação completa das questões via IA')], default='manual', max_length=20, verbose_name='forma de montagem'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assembly_notes',
            field=models.TextField(blank=True, verbose_name='resultado da montagem'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assembly_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta'), ('failed', 'Falha na montagem')], default='draft', max_length=10, verbose_name='status da montagem'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='desired_question_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quantidade desejada de questões'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='generation_prompt',
            field=models.TextField(blank=True, verbose_name='instruções para montagem'),
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='matéria')),
                ('topic', models.CharField(max_length=160, verbose_name='assunto')),
                ('statement', models.TextField(verbose_name='enunciado')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla escolha'), ('open_ended', 'Discursiva')], default='multiple_choice', max_length=24, verbose_name='formato da questão')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='alternativas')),
                ('correct_answer', models.TextField(blank=True, verbose_name='gabarito ou resposta esperada')),
                ('explanation', models.TextField(blank=True, verbose_name='explicação do gabarito')),
                ('default_points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='pontuação padrão')),
                ('creation_method', models.CharField(choices=[('manual', 'Criação manual'), ('derived', 'Edição de questão existente'), ('ai_edited', 'Questão existente editada por IA'), ('ai_generated', 'Questão nova gerada por IA')], default='manual', max_length=16, verbose_name='origem')),
                ('ai_instructions', models.TextField(blank=True, verbose_name='instruções enviadas à IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_items', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_questions', to='assessments.questionbankitem', verbose_name='questão de origem')),
            ],
            options={
                'verbose_name': 'questão do banco',
                'verbose_name_plural': 'banco de questões',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bank_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_copies', to='assessments.questionbankitem', verbose_name='item do banco'),
        ),
    ]
