# Generated by Django 5.2.5 on 2026-09-22 11:49

from django.db import migrations


def copy_existing_questions_to_bank(apps, schema_editor):
    Question = apps.get_model("assessments", "Question")
    QuestionBankItem = apps.get_model("assessments", "QuestionBankItem")
    Assessment = apps.get_model("assessments", "Assessment")
    assessment_ids = set()
    for question in Question.objects.select_related("assessment").filter(bank_item__isnull=True):
        assessment = question.assessment
        bank_item = QuestionBankItem.objects.create(
            owner_id=assessment.owner_id,
            subject=assessment.subject,
            topic=assessment.topic,
            statement=question.statement,
            question_type=question.question_type,
            options=question.options,
            correct_answer=question.correct_answer,
            explanation=question.explanation,
            default_points=question.points,
            creation_method="manual",
        )
        question.bank_item_id = bank_item.pk
        question.save(update_fields=("bank_item",))
        assessment_ids.add(assessment.pk)
    Assessment.objects.filter(pk__in=assessment_ids).update(
        assembly_status="ready",
        assembly_notes="Questões existentes migradas para o banco reutilizável.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_assembly_method_assessment_assembly_notes_and_more'),
    ]

    operations = [migrations.RunPython(copy_existing_questions_to_bank, migrations.RunPython.noop)]
