# Generated by Django 5.2.5 on 2026-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('MEMBER', 'Usuário'), ('MANAGER', 'Gestor'), ('ADMIN', 'Administrador'), ('SYSADMIN', 'Administrador de sistema')], default='MEMBER', max_length=16, verbose_name='papel no sistema'),
        ),
    ]
