# Generated by Django 5.2.5 on 2026-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Acompanhar o dispositivo'), ('light', 'Claro'), ('dark', 'Escuro')], default='system', max_length=8, verbose_name='aparência'),
        ),
    ]
