# Generated by Django 5.2.5 on 2026-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/', verbose_name='foto de perfil'),
        ),
    ]
