# Generated by Django 5.2.5 on 2026-09-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="SavedAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="título")),
                ("scope_title", models.CharField(max_length=160, verbose_name="escopo")),
                ("period_label", models.CharField(max_length=80, verbose_name="período")),
                ("filters", models.JSONField(default=dict, verbose_name="filtros")),
                ("snapshot", models.JSONField(default=dict, verbose_name="resultado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        )
    ]
