# Generated by Django 5.2.5 on 2026-08-18 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='educationalrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('requested_by', models.F('teacher')), ('requested_by', models.F('student')), _connector='OR'), name='relationship_requester_is_participant'),
        ),
    ]
