# Generated by Django 5.2.5 on 2026-08-19 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_classrooms(apps, schema_editor):
    Classroom = apps.get_model('users_manager', 'Classroom')
    ClassroomMembership = apps.get_model('users_manager', 'ClassroomMembership')
    Organization = apps.get_model('users_manager', 'Organization')
    OrganizationMembership = apps.get_model('users_manager', 'OrganizationMembership')

    organizations_by_owner = {}
    for classroom in Classroom.objects.all():
        organization = organizations_by_owner.get(classroom.owner_id)
        if organization is None:
            organization = Organization.objects.create(
                name=f"Organização de {classroom.owner}",
                description="Organização criada automaticamente a partir das turmas existentes.",
                owner_id=classroom.owner_id,
            )
            organizations_by_owner[classroom.owner_id] = organization
            OrganizationMembership.objects.create(
                organization=organization,
                user_id=classroom.owner_id,
                is_teacher=True,
                added_by_id=classroom.owner_id,
            )

        classroom.organization = organization
        classroom.save(update_fields=('organization',))

        for classroom_membership in ClassroomMembership.objects.filter(
            classroom=classroom,
            status='ACTIVE',
        ):
            membership, _ = OrganizationMembership.objects.get_or_create(
                organization=organization,
                user_id=classroom_membership.user_id,
                defaults={
                    'is_teacher': classroom_membership.role == 'TEACHER',
                    'is_student': classroom_membership.role == 'STUDENT',
                    'added_by_id': classroom.owner_id,
                },
            )
            if classroom_membership.role == 'TEACHER' and not membership.is_teacher:
                membership.is_teacher = True
                membership.save(update_fields=('is_teacher',))
            if classroom_membership.role == 'STUDENT' and not membership.is_student:
                membership.is_student = True
                membership.save(update_fields=('is_student',))


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0002_educationalrelationship_relationship_requester_is_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('instructions', models.TextField(blank=True, verbose_name='instruções')),
                ('max_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='pontuação máxima')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users_manager.classroom', verbose_name='turma')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_classroom_tests', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users_manager.organization', verbose_name='organização'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='professor')),
                ('is_student', models.BooleanField(default=False, verbose_name='aluno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_members_added', to=settings.AUTH_USER_MODEL, verbose_name='adicionado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users_manager.organization', verbose_name='organização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'ordering': ('user__username',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_user_per_organization'), models.CheckConstraint(condition=models.Q(('is_teacher', True), ('is_student', True), _connector='OR'), name='organization_member_has_educational_role')],
            },
        ),
        migrations.RunPython(migrate_existing_classrooms, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users_manager.organization', verbose_name='organização'),
        ),
    ]
