# Generated by Django 5.2.5 on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users_manager", "0004_classroom_groups_letters_and_shifts")]

    operations = [
        migrations.AddField(
            model_name="classroomgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="users_manager.classroomgroup",
                verbose_name="grupo pai",
            ),
        )
    ]
