# Generated by Django 5.2.5 on 2026-09-22 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import features.users_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0005_classroomgroup_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180, verbose_name='razão social')),
                ('display_name', models.CharField(max_length=180, verbose_name='nome da escola')),
                ('school_type', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], max_length=10, verbose_name='tipo')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('inep_code', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='código INEP')),
                ('address', models.CharField(max_length=240, verbose_name='endereço')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aprovada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_schools', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='school', to='users_manager.organization', verbose_name='organização operacional')),
            ],
            options={
                'verbose_name': 'escola credenciada',
                'verbose_name_plural': 'escolas credenciadas',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=180, verbose_name='razão social')),
                ('display_name', models.CharField(max_length=180, verbose_name='nome da escola')),
                ('school_type', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], max_length=10, verbose_name='tipo')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('inep_code', models.CharField(blank=True, max_length=12, verbose_name='código INEP')),
                ('address', models.CharField(max_length=240, verbose_name='endereço')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=10, verbose_name='status')),
                ('review_notes', models.TextField(blank=True, verbose_name='parecer')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='users_manager.school', verbose_name='escola aprovada')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_applications', to=settings.AUTH_USER_MODEL, verbose_name='gestor solicitante')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_school_applications', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'solicitação de escola',
                'verbose_name_plural': 'solicitações de escolas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SchoolVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='school_applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'jpg', 'jpeg', 'png')), features.users_manager.models.validate_school_document_size], verbose_name='arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='nome original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users_manager.schoolapplication', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'documento comprobatório',
                'verbose_name_plural': 'documentos comprobatórios',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
