# Generated by Django 5.2.5 on 2026-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0006_school_schoolapplication_schoolverificationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id_snapshot', models.PositiveBigIntegerField(verbose_name='ID da organização')),
                ('organization_name', models.CharField(max_length=120, verbose_name='nome da organização')),
                ('trigger', models.CharField(choices=[('ORGANIZATION_DELETE', 'Exclusão de organização'), ('SCHOOL_DELETE', 'Exclusão de escola')], max_length=24, verbose_name='origem')),
                ('file', models.FileField(upload_to='institution_exports/%Y/%m/', verbose_name='arquivo CSV')),
                ('row_count', models.PositiveIntegerField(verbose_name='linhas exportadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'exportação de instituição',
                'verbose_name_plural': 'exportações de instituições',
                'ordering': ('-created_at',),
            },
        ),
    ]
