# Generated by Django 5.2.5 on 2026-09-28 16:47

import secrets

import django.db.models.deletion
import features.users_manager.models
from django.db import migrations, models


def populate_codes(apps, schema_editor):
    School = apps.get_model('users_manager', 'School')
    schools = School.objects.using(schema_editor.connection.alias)
    used = set()
    for school in schools.all().iterator():
        code = 'LUM-' + secrets.token_hex(8).upper()
        while code in used:
            code = 'LUM-' + secrets.token_hex(8).upper()
        used.add(code)
        schools.filter(pk=school.pk).update(institutional_code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0007_institutiondataexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='institutional_code',
            field=models.CharField(null=True, editable=False, max_length=20, unique=True, verbose_name='código institucional'),
        ),
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='school',
            name='institutional_code',
            field=models.CharField(default=features.users_manager.models.generate_institutional_code, editable=False, max_length=20, unique=True, verbose_name='código institucional'),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_enabled',
            field=models.BooleanField(default=True, verbose_name='cadastro por código habilitado'),
        ),
        migrations.CreateModel(
            name='InstitutionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=180, verbose_name='instituição')),
                ('contact_name', models.CharField(max_length=150, verbose_name='nome do responsável pelo contato')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone / WhatsApp')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('message', models.TextField(blank=True, max_length=3000, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('NEW', 'Novo contato'), ('CONTACTED', 'Em atendimento'), ('COMPLETED', 'Instituição cadastrada'), ('CLOSED', 'Encerrado')], default='NEW', max_length=12, verbose_name='situação')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_manager.school', verbose_name='instituição cadastrada')),
            ],
            options={
                'verbose_name': 'contato institucional',
                'verbose_name_plural': 'contatos institucionais',
                'ordering': ['-created_at'],
            },
        ),
    ]
