# Generated by Django 5.2.5 on 2026-09-28 18:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0008_school_institutional_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='institutional_code',
        ),
        migrations.RemoveField(
            model_name='school',
            name='registration_enabled',
        ),
        migrations.AddField(
            model_name='school',
            name='email_domain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='domínio dos e-mails institucionais'),
        ),
        migrations.CreateModel(
            name='InstitutionalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=40, verbose_name='matrícula / registro')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='e-mail institucional')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrativo'), ('STUDENT', 'Estudante'), ('TEACHER', 'Professor')], max_length=10, verbose_name='perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioned_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_accounts', to='users_manager.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acesso institucional',
                'verbose_name_plural': 'acessos institucionais',
                'ordering': ['role', 'registration'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'registration'), name='unique_institution_registration'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_institution_email_lower'), models.UniqueConstraint(condition=models.Q(('role', 'ADMIN')), fields=('organization',), name='one_institution_admin')],
            },
        ),
    ]
