# Generated by Django 5.2.5 on 2026-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0009_remove_school_institutional_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalaccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrativo'), ('STUDENT', 'Estudante'), ('TEACHER', 'Professor'), ('MANAGER', 'Gestor'), ('OPERATOR', 'Operador'), ('GUARDIAN', 'Responsável')], max_length=10, verbose_name='perfil'),
        ),
    ]
